import { nanoid } from 'nanoid';

export const list = [
  {
    id: nanoid(),
    image: '/hero-img-1.jpg',
    name: 'Read more',
    title: 'Forge Your Future: Explore Precision Welding Tools',
    quote:
      'Emphasizes the idea of growth and advancement in welding skills through the use of high-quality, precise tools.',
    link1: '/about',
  },
  {
    id: nanoid(),
    image: '/hero-img-2.jpg',
    name: 'Read more',
    title:
      'Craftsmanship Redefined: Quality Welding Equipment at Your Fingertips',
    quote:
      'Highlights the focus on top-notch welding equipment that enhances craftsmanship and attention to detail.',
    link1: '/services',
  },
  {
    id: nanoid(),
    image: '/hero-img-3.jpg',
    name: 'Read more',
    title: 'Spark Your Creativity: Discover Innovative Welding Solutions',
    quote:
      'Encourages creativity and innovation in welding projects by introducing new and inventive solutions.',
    link1: '/services',
  },
  {
    id: nanoid(),
    image: '/hero-img-4.jpg',
    name: 'Read more',
    title: 'Ignite Your Skills: Unleash the Power of Precision Welding',
    quote:
      'Encourages users to enhance their welding skills by utilizing tools that provide precision and accuracy.',
    link1: '/services',
  },
  {
    id: nanoid(),
    image: '/hero-img-5.jpg',
    name: 'Read more',
    title: 'Weld with Confidence: Trusted Tools for Every Project',
    quote:
      'Instills confidence in users by offering reliable and trusted tools suitable for a wide range of welding projects.',
    link1: '/services',
  },
  {
    id: nanoid(),
    image: '/hero-img-6.jpg',
    name: 'Read more',
    title: 'Precision Meets Passion: Elevate Your Welding Experience',
    quote:
      'Combines the precision of tools with the passion for welding, promising an elevated and fulfilling welding experience.',
    link1: '/services',
  },
  {
    id: nanoid(),
    image: '/hero-img-7.jpg',
    name: 'Read more',
    title: 'Explore, Weld, Create: Your Journey Starts Here',
    quote:
      'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    link1: '/services',
  },
  {
    id: nanoid(),
    image: '/hero-img-9.jpg',
    name: 'Read more',
    title: 'Empower Your Craft: Quality Tools for Every Welding Task',
    quote:
      'Focuses on empowering users to excel in their craft by providing quality tools that cater to every welding task they may encounter.',
    link1: '/services',
  },
];

export const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'decoratives',
    price: 15.99,
    img: '/01.jpg',
    desc: `Lorem Ipsum dollor sit `,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-1',
  },
  {
    id: 2,
    title: 'diner double',
    category: 'facades',
    price: 13.99,
    img: '/02.jpg',
    desc: `Lorem Ipsum dollor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-2',
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'perforated',
    price: 6.99,
    img: '/03.jpg',
    desc: `Lorem Ipsum dollor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-3',
  },
  {
    id: 4,
    title: 'country delight',
    category: 'railings',
    price: 20.99,
    img: '/04.jpg',
    desc: `Lorem Ipsum dollor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-4',
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'decoratives',
    price: 22.99,
    img: '/05.jpg',
    desc: `Lorem Ipsum dollor sit  `,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-5',
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'facades',
    price: 18.99,
    img: '/06.jpg',
    desc: `Lorem ipsum dolor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
  {
    id: 7,
    title: 'oreo dream',
    category: 'perforated',
    price: 18.99,
    img: '/07.jpg',
    desc: `Lorem ipsum dolor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
  {
    id: 8,
    title: 'oreo dream',
    category: 'railings',
    price: 18.99,
    img: '/08.jpg',
    desc: `Lorem ipsum dolor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
  {
    id: 9,
    title: 'oreo dream',
    category: 'decoratives',
    price: 18.99,
    img: '/09.jpg',
    desc: `Lorem ipsum dolor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
  {
    id: 10,
    title: 'oreo dream',
    category: 'facades',
    price: 18.99,
    img: '/10.jpg',
    desc: `Lorem ipsum dolor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
  {
    id: 11,
    title: 'oreo dream',
    category: 'perforated',
    price: 18.99,
    img: '/11.jpg',
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
  {
    id: 12,
    title: 'oreo dream',
    category: 'railings',
    price: 18.99,
    img: '/12.jpg',
    desc: `Lorem ipsum dolor sit`,
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    name: 'project-6',
  },
];

export const team = [
  {
    id: 1,
    name: 'Nicholas Putnam',
    title: 'controller',
    img: '/team1.jpg',
    text: 'A seasoned welder with over a decade of experience, combines technical skill with a passion for precision.',
    link: '/',
  },
  {
    id: 2,
    name: 'Richard Williams',
    title: 'Welder',
    img: '/team2.jpg',
    text: 'A dynamic welder with over eight years of hands-on experience in the field, renowned for her innovative approach and exceptional skill.',
    link: '/',
  },
  {
    id: 3,
    name: 'David Blankenship',
    title: 'Locksmith',
    img: '/team3.jpg',
    text: 'A highly skilled welder with over 15 years of experience in the trade, known for his expertise in both structural and pipe welding.',
    link: '/',
  },
  {
    id: 4,
    name: 'Zachary Guzman',
    title: 'Locksmith',
    img: '/team4.jpg',
    text: 'A versatile welder with over a decade of experience specializing in both commercial and residential projects.',
    link: '/',
  },
  {
    id: 5,
    name: 'Jeremiah Evans',
    title: 'Controller',
    img: '/team5.jpg',
    text: 'Invites users to embark on a journey of exploration, welding, and creation with the resources and tools available on the website.',
    link: '/',
  },
];

export const blog = [
  {
    id: 1,
    name: 'Nicholas Putnam',
    category: 'News',
    title: 'controller',
    img: '/blog1.jpg',
    text: 'A seasoned welder with over a decade of experience, combines technical skill with a passion for precision.',
    link: '/',
  },
  {
    id: 2,
    name: 'Richard Williams',
    category: 'News',
    title: 'Welder',
    img: '/blog2.jpg',
    text: 'A dynamic welder with over eight years of hands-on experience in the field, renowned for her innovative approach and exceptional skill.',
    link: '/',
  },
  {
    id: 3,
    name: 'David Blankenship',
    category: 'News',
    title: 'Locksmith',
    img: '/blog3.jpg',
    text: 'A highly skilled welder with over 15 years of experience in the trade, known for his expertise in both structural and pipe welding.',
    link: '/',
  },
];
